### ISSUE TITLE
1.4.0 Rendering Regression: Canvas Tags are Redrawn

### ISSUE THREAD

**Issue by maxcountryman** [gor181/react-chartjs-2#46]
It seems that in versions greater than 1.2.8 (starting definitively with 1.4.0) there is a rendering regression where the entire canvas tag is reloaded upon the click event of a href. For my application this is undesirable because there are tabs which correspond to tabular data that make use of hrefs. I don't know what precisely caused this (I'll have a look at the commits tomorrow if I have time) but I can assume it was likely unintentional and so wanted to report it ASAP.

**Comment by gor181** [comment]
hey @maxcountryman 

Apologies for late reply. So when you click on an anchor the whole canvas is re-rendered?
Please confirm so I can test it a bit.

Cheers,

**Comment by maxcountryman** [comment]
Not a problem. That's exactly right.

**Comment by jerairrest** [comment]
@gor181 Was this fixed in 1.6.0?

**Comment by gor181** [comment]
Yap should be. at least tests are saying so

On Dec 9, 2016 14:56, "Jeremy Ayerst" <notifications@github.com> wrote:

@gor181 <https://github.com/gor181> Was this fixed in 1.6.0?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/gor181/react-chartjs-2/issues/46#issuecomment-266019349>,
or mute the thread

**Comment by jerairrest** [comment]
Ok! Closing for now. @maxcountryman if you're still seeing an issue please reopen!

Thanks!

Jer

**Comment by maxcountryman** [comment]
Seems to be working. 👍
